name: HungerOnRespawn
version: 1.0
main: com.hungeronrespawn.HungerOnRespawnPlugin
description: Sets player hunger level upon respawn.
commands:
  hungeronrespawn:
    description: HungerOnRespawn plugin commands
    usage: /<command> [reload|help]
    permission: hungeronrespawn.use
    permission-message: You do not have permission to use this command.
permissions:
  hungeronrespawn.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  hungeronrespawn.help:
    description: Allows the player to view help information
    default: op
  hungeronrespawn.bypass:
    description: Allows the player to bypass hunger modification
    default: op
